receivers:
  otlp:
    protocols:
      http:
      grpc:
  prometheus:
    config:
      scrape_configs:
        - job_name: "example"
          scrape_interval: 5s
          metrics_path: '/actuator/prometheus'
          static_configs:
            - targets: ["app:8080"]

processors:
  # batch metrics before sending to reduce API usage
  batch:

exporters:
#  logging:
#    loglevel: debug
#
#  loki:
#    endpoint: "http://loki:3100/loki/api/v1/push"

#  prometheus:
#    endpoint: "0.0.0.0:8889"
#    const_labels:
#      label1: value1

#  otlp:
#    endpoint: tempo:4317
#    tls:
#      insecure: true
#
#  zipkin:
#    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
#    format: proto

  otlp:
    endpoint: 172.20.17.150:4317
    tls:
      insecure: true

# https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/README.md
extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:
  # fetches the collectorâ€™s performance data
  pprof:
  # serves as an http endpoint that provides live debugging data about instrumented components.
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [otlp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
#      exporters: [jaeger,zipkin,otlp]
#    logs:
#      receivers: [otlp]
#      exporters: [loki]
